Creato oggetto Match
d-u-d-e/FindSoccerPlayers pull request #6
Opened 2020-05-21 13:35 UTC by kzmdti

Aggiunte activity per la creazione della partita, mappa, e oggetto Match per la partita

2020-05-21 15:53 UTC, lucagiordano-visia requested changes

2020-05-21 15:53 UTC, giordy16 commented on app/src/main/java/com/es/findsoccerplayers/MainActivity.java
> +            case R.id.create_match:
Seguendo il layout delle activity che ho caricato sta mattina, per creare una partita dovremmo fare un FTB

2020-05-21 15:53 UTC, giordy16 commented on app/src/main/java/com/es/findsoccerplayers/MainActivity.java
> +                    // else just start the activity
Quando starti un nuova activity, metti i flag nell'intent per dirgli di usare l'activity già presente nello stack, senza doverla creare di nuovo

2020-05-21 15:53 UTC, giordy16 commented on app/src/main/res/menu/map_options.xml
> +        app:showAsAction="never"/>
io terrei solo normal view e satelite, poichè normal ha tutti i segnalini delle posizioni che servono a noi, mentre satelite può tornare utile quando non sai dov'è il campo e vuoi cercarlo dal satellite. Le altre due non servono a molto a mio parere

2020-05-21 15:53 UTC, giordy16 commented on app/src/main/res/menu/map_options.xml
> +        app:showAsAction="always"/>
Per la conferma della posizione penso sia più carino un FTB con una spunta, se si può fare

2020-05-21 15:53 UTC, giordy16 commented on app/src/main/res/layout/activity_match.xml
> +            app:layout_constraintTop_toBottomOf="@id/date_hour" />
Io qui troverei più intuitivo mettere due stringhe "SELEZIONA DATA" "SELEZIONA ORA" al posto di mettere data e ora attuali, un po' come ho fatto su Registe

2020-05-21 15:53 UTC, giordy16 commented on app/src/main/res/layout/activity_match.xml
> +
ci sarebbe da aggiungere la toolbat con la freccia di back come nelle altre activity

2020-05-21 15:53 UTC, giordy16 commented on app/src/main/res/layout/activity_maps.xml
> +<?xml version="1.0" encoding="utf-8"?>
ci sarebbe da aggiungere la freccia di back come nelle altre activity

2020-05-23 09:55 UTC, d-u-d-e requested changes

2020-05-23 09:55 UTC, d-u-d-e commented on app/src/main/java/com/es/findsoccerplayers/MainActivity.java
> +                //If we have a last know location of the user, send it to the MatchActivity
"known"

2020-05-23 09:55 UTC, d-u-d-e commented on app/src/main/java/com/es/findsoccerplayers/MainActivity.java
> +                }
togli l'`else` e scrivi dentro l'`if` solo i `putExtra`

2020-05-23 09:55 UTC, d-u-d-e commented on app/src/main/java/com/es/findsoccerplayers/MyPickers/DatePickerFragment.java
>          setTheDate(dayOfMonth, month+ 1, year);
lo chiamerei `setDate`

2020-05-23 09:55 UTC, d-u-d-e commented on app/src/main/java/com/es/findsoccerplayers/MatchActivity.java
> +    private final String LOGITUDE = "longitude";
"LONGITUDE"

2020-05-23 10:22 UTC, d-u-d-e requested changes

2020-05-23 10:22 UTC, d-u-d-e commented on app/src/main/java/com/es/findsoccerplayers/MainActivity.java
> +                        Toast.makeText(MainActivity.this, R.string.gps_disabled_toast, Toast.LENGTH_SHORT).show();
TODO

2020-05-23 10:22 UTC, d-u-d-e commented on app/src/main/java/com/es/findsoccerplayers/MyPickers/NumberPickerDialog.java
> +        alertDialog.setTitle("Quanti giocatori ti mancano?").setView(np).setPositiveButton("OK", new DialogInterface.OnClickListener() {
hardcoded string

2020-05-23 10:22 UTC, d-u-d-e commented on app/src/main/res/values/strings.xml
> +
diamogli un nome coerente con gli altri, aggiungendo davanti il nome dell'activity come negli altri casi

2020-05-23 10:22 UTC, d-u-d-e commented on app/src/main/java/com/es/findsoccerplayers/MapsActivity.java
> +                    Toast.makeText(MapsActivity.this, R.string.gecodo_failed, Toast.LENGTH_SHORT).show();
se fallisce assegna a `placename` semplicemente la posizione di default, senza toast o print dello stack trace

2020-05-28 11:28 UTC, closed without merging